name: Deploy to Server

on:
  workflow_run:
    workflows: ["Next.js + Express"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          timeout: 300s
          script: |
            cd ~/solana-day/
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up --build -d

            sudo docker image prune -f

            sleep 10

            sudo docker-compose ps
